### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by schjonhaug** [zwerch/homebridge-webos2#1]
The instructions say 

`sudo npm install -g homebridge-websocket`

But how do I actually install home bridge-webos?

Should I do

`sudo npm install -g homebridge-webos` ?

**Comment by zwerch** [comment]
Thanks for your issue. This was a simple copy & paste error.
I also didn't publish the project with `npm`.

And I had to rename it because of another project with the same name (which seems to be doing nothing at all).

You can install it with:
`sudo npm install -g homebridge-webos2`
