### ISSUE TITLE
WebOs3

### ISSUE THREAD

**Issue by m11rphy** [zwerch/homebridge-webos2#3]
Hi I have an LG TV with webOS3, every is installed ok but this won't turn on the TV is there something I can change for webOS3 ?

**Comment by zwerch** [comment]
I am not able to test it with webOS 3, but the turning on is done by [Wake On LAN](https://en.wikipedia.org/wiki/Wake-on-LAN). I think it's the same thing that remote controlling apps do to turn it on.

I don't know if this feature is also enabled for a wifi connection but I think it's possible.

**Comment by m11rphy** [comment]
I'm able to use the LG iOS app to control the TV, but your plugin just crashes

**Comment by zwerch** [comment]
@m11rphy I know, and I'm sorry, but I currently don't have the time for further development. Please contribute if you can!
